name: CI Pipeline
on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  lint-flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run flake8
        run: |
          poetry run flake8 src

  lint-mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run mypy
        run: |
          poetry run mypy src

  tests-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run api tests with coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml -m api

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-api
          path: coverage.xml

  tests-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run integration tests with coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml -m integration

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: coverage.xml

  tests-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run unit tests with coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml -m unit

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage.xml


  tests-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run validation tests with coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml -m validation

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-validation
          path: coverage.xml
